#!/bin/bash
set -ev
cd "$(dirname "${BASH_SOURCE[0]}")"
UNICODES=${UNICODES:-'16 32'}
PYTHONS=${PYTHONS:-'2.7 3.3 3.4 3.5 3.6'}
ARCHS=${ARCHS:-'x86_64 i686'}
IMAGESRC=${IMAGESRC:-quay.io/pypa}
REPO=${REPO:-https://bitbucket.org/rptlab/reportlab}
BRANCH=${BRANCH:-default}
REQUIREMENT=${REQUIREMENT:-$(basename ${REPO})}
DOCKER_SCRIPT=${DOCKER_SCRIPT:-container-build-wheels}
DOCKER_PATH=${DOCKER_PATH:-/io/${DOCKER_SCRIPT}}

sudo rm -rf wheels wheelsu .pip-cache
mkdir wheels wheelsu
for arch in ${ARCHS}; do
	sudo rm -rf wheelhouse wheels_unfixed
	mkdir wheelhouse wheels_unfixed
	DOCKER_IMAGE=${IMAGESRC}/manylinux1_${arch}
	docker pull $DOCKER_IMAGE
	docker run --rm \
		${DOCKER_ARGS} \
		-e PYTHONS="$PYTHONS" \
		-e UNICODES="$UNICODES" \
		-e REPO="$REPO" \
		-e BRANCH="$BRANCH" \
		-e REQUIREMENT="$REQUIREMENT" \
		-e ARCH="$arch" \
		-v $(pwd):/io ${DOCKER_IMAGE}  ${DOCKER_PATH}
	cp wheelhouse/* wheels/
	cp wheels_unfixed/* wheelsu/
done
sudo rm -rf wheels_unfixed wheelhouse
