#!/bin/bash
set -ev
cd "$(dirname "${BASH_SOURCE[0]}")"
UNICODE_WIDTHS='16 32'
PYTHON_VERSIONS='2.7 3.3 3.4 3.5 3.6'
ARCHS='x86_64 i686'
IMAGESRC=quay.io/pypa
REPO=${REPO:-https://bitbucket.org/rptlab/reportlab}
REQUIREMENT=${REPO:-$(basename ${REPO})}
DOCKER_SCRIPT=${DOCKER_SCRIPT:-container-build-wheels}
DOCKER_PATH=${DOCKER_PATH:-/io/${DOCKER_SCRIPT}}
#IMAGESRC=rl
sudo rm -rf wheels wheelsu
mkdir wheels wheelsu
for arch in ${ARCHS}; do
	sudo rm -rf wheelhouse wheels_unfixed
	mkdir wheelhouse wheels_unfixed
	DOCKER_IMAGE=${IMAGESRC}/manylinux1_${arch}
	docker pull $DOCKER_IMAGE
	docker run --rm \
		${DOCKER_ARGS} \
		-e PYTHON_VERSIONS="$PYTHON_VERSIONS" \
		-e UNICODE_WIDTHS="$UNICODE_WIDTHS" \
		-e REPO="$REPO" \
		-e REQUIREMENT="$REQUIREMENT" \
		-e ARCH="$arch" \
		-v $(pwd):/io ${DOCKER_IMAGE}  ${DOCKER_PATH}
	cp wheelhouse/* wheels/
	cp wheels_unfixed/* wheelsu/
done
sudo rm -rf wheels_unfixed wheelhouse
