#!/bin/bash
UNICODE_WIDTHS='16 32'
PYTHON_VERSIONS='2.7 3.3 3.4 3.5 3.6'
ARCHS='x86_64 i686'
IMAGESRC=quay.io/pypa
REPO=${REPO:-https://bitbucket.org/rptlab/reportlab}
REQUIREMENT=${REPO:-$(basename ${REPO})}
DOCKER_SCRIPT=${DOCKER_SCRIPT:-container-test-wheels}
sudo rm -rf test-src
hg clone ${REPO} test-src
[ -n "$REVISION" ] && (cd test-src && hg up "$REVISION")
#IMAGESRC=rl
for arch in ${ARCHS}; do
	DOCKER_IMAGE=${IMAGESRC}/manylinux1_${arch}
	docker run --rm \
		-e PYTHON_VERSIONS="$PYTHON_VERSIONS" \
		-e UNICODE_WIDTHS="$UNICODE_WIDTHS" \
		-e REPO="$REPO" \
		-e REEQUIREMENT="$REQUIREMENT" \
		-e ARCH="$arch" \
		-v $(pwd):/io ${IMAGESRC}/manylinux1_${arch} /io/rl_ci_tools/manylinux/${DOCKER_SCRIPT}
done
sudo rm -rf reportlab-src test-env
